//FUNCIONES RELACIONADAS CON LA NAVBAR LATERAL

export const NAVBARLATERAL_ABIERTA = 'NAVBARLATERAL_ABIERTA'
export const NAVBARLATERAL_CERRADA = 'NAVBARLATERAL_CERRADA'


//FUNCIONES PARA OBTENER LOS PRODUCTOS
export const GET_PRODUCTOS_INICIAL = 'GET_PRODUCTOS_INICIAL'
export const GET_PRODUCTOS_CORRECTO = 'GET_PRODUCTOS_CORRECTO'
export const GET_PRODUCTOS_ERROR = 'GET_PRODUCTOS_ERROR'
