//FUNCIONES RELACIONADAS CON LA NAVBAR LATERAL

export const NAVBARLATERAL_ABIERTA = 'NAVBARLATERAL_ABIERTA'
export const NAVBARLATERAL_CERRADA = 'NAVBARLATERAL_CERRADA'


//FUNCIONES PARA OBTENER LOS PRODUCTOS
export const GET_PRODUCTOS_INICIAL = 'GET_PRODUCTOS_INICIAL'
export const GET_PRODUCTOS_CORRECTO = 'GET_PRODUCTOS_CORRECTO'
export const GET_PRODUCTOS_ERROR = 'GET_PRODUCTOS_ERROR'


//FUNCIONES PARA OBTENER UN PRODUCTO INDIVIDUAL
export const GET_PRODUCTO_INDIVIDUAL_INICIAL = 'GET_PRODUCTO_INDIVIDUAL_INICIAL'
export const GET_PRODUCTO_INDIVIDUAL_CORRECTO = 'GET_PRODUCTO_INDIVIDUAL_CORRECTO'
export const GET_PRODUCTO_INDIVIDUAL_ERROR = 'GET_PRODUCTO_INDIVIDUAL_ERROR'


//FUNCIONES RELACIONADAS CON EL FILTRO DE LOS PRODCUTOS TOTALES
export const CARGAR_PRODUCTOS = 'CARGAR_PRODUCTOS'

//FUNCIONES RELACIONADAS CON EL LAS PREFERENCIAS DE VISTA DE LOS PRODUCTOS
export const SET_VISTA_CUADRICULA = 'SET_VISTA_CUADRICULA'
export const SET_VISTA_LISTA = 'SET_VISTA_LISTA'

//FUNCIONES RELACIONADAS CON ORDENAR
export const ACTUALIZAR_ORDER_BY = 'ACTUALIZAR_ORDER_BY'
export const ORDENAR = 'ORDENAR'

//FUNCIONES RELACIONADAS CON FILTRAR
export const ACTUALIZAR_FILTROS = 'ACTUALIZAR_FILTROS'
export const FILTRAR_PRODUCTOS = 'FILTRAR_PRODUCTOS'